[package]
name = "chord_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
rand = "0.8.5"
sarge = "7.2.4"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
strum = "0.26.3"
strum_macros = "0.26.4"
